export const GAME_CONFIG = {
  targetRadius: 30,
  targetHitRadius: 56,
  targetSpawnTop: 130,
  targetSideMargin: 62,
  dragDistance: 120,
  dragPathTolerance: 72,
  perfectScore: 150,
  goodScore: 100,
  comboBonus: 10,
  flowMax: 100,
  flowPerfectGain: 25,
  flowGoodGain: 12,
  flowMissPenalty: 30,
  flowDuration: 8,
  flowScoreMultiplier: 2,
  flowPerfectTimeBonus: 0.65,
  superFlowPerfectRequirement: 4,
  superFlowScoreMultiplier: 4,
  superFlowPerfectTimeBonus: 0.85,
  superFlowFallbackTime: 3.5,
} as const;
